'use strict';

async function postComment(params) {
  const url = `https://api.github.com/repos/${params.owner}/${params.repo}/issues/${params.prNumber}/comments`;
  const response = await fetch(url, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Accept': 'application/vnd.github+json',
      'User-Agent': 'drift-guardian',
      Authorization: `Bearer ${params.token}`
    },
    body: JSON.stringify({ body: params.body }),
    signal: AbortSignal.timeout(30000) // 30 second timeout
  });

  if (!response.ok) {
    const text = await response.text();
    throw new Error(
      `Failed to post PR comment to ${params.owner}/${params.repo}#${params.prNumber}.\n` +
      `Status: ${response.status}\n` +
      `Response: ${text.slice(0, 500)}${text.length > 500 ? '...' : ''}\n` +
      'Check that GITHUB_TOKEN has pull-requests:write permission.'
    );
  }
}

function formatResultsMarkdown(results, config) {
  if (!results || results.length === 0) {
    return 'Drift Guardian: no drift detected.';
  }

  const errors = results.filter((r) => r.severity === 'error' || r.severity === 'critical');
  const warnings = results.filter((r) => r.severity === 'warning');
  const infos = results.filter((r) => r.severity === 'info');

  let body = '## Drift Guardian Results\n';

  if (errors.length > 0) {
    body += '\n### Errors\n';
    body += formatList(errors);
  }

  if (warnings.length > 0) {
    body += '\n\n### Warnings\n';
    body += formatList(warnings);
  }

  if (infos.length > 0) {
    body += '\n\n### Info\n';
    body += formatList(infos);
  }

  body += '\n\n---\nGenerated by Drift Guardian';
  return body;
}

function formatList(items) {
  return items.map((item) => {
    const parts = [];
    parts.push(`[${item.source}] ${item.type}`);
    if (item.rule) {
      parts.push(`rule: ${item.rule}`);
    }
    if (item.file) {
      parts.push(`file: ${item.file}`);
    }
    if (item.policySection) {
      parts.push(`policy: ${item.policySection}`);
    }
    if (item.explanation) {
      parts.push(item.explanation);
    }
    if (item.suggestion) {
      parts.push(`suggestion: ${item.suggestion}`);
    }
    return `- ${parts.join(' | ')}`;
  }).join('\n');
}

module.exports = {
  postComment,
  formatResultsMarkdown
};
